[package]
name = "freeswitch-esl"
version = "0.1.0"
authors = ["KaranGauswami <karangauswami.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
log = { version = "0.4.14", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
anyhow = { version = "*" }
env_logger = "0.9.0"
